(load "~/.config/emacs/emacs.d/options.el")
(load "~/.config/emacs/emacs.d/packages.el")
(load "~/.config/emacs/emacs.d/keybinds.el")
(load "~/.config/emacs/emacs.d/lsp.el")
(load "~/.config/emacs/emacs.d/tree-sitter.el")
(load "~/.config/emacs/emacs.d/org.el")
